stats:
  gol:
    id: G
    pos: [gol, zag, lat, mei, ata]
    score: 8
  assistencias:
    id: A
    pos: [gol, zag, lat, mei, ata]
    score: 5
  finalizacao_def:
    id: FD
    pos: [gol, zag, lat, mei, ata]
    score: 1.2
  finalizacao_fora:
    id: FF
    pos: [gol, zag, lat, mei, ata]
    score: 0.8
  falta_sofrida:
    id: FS
    pos: [gol, zag, lat, mei, ata]
    score: 0.5
  impedimento:
    id: I
    pos: [gol, zag, lat, mei, ata]
    score: -0.1
  passe_incompleto:
    id: PI
    pos: [gol, zag, lat, mei, ata]
    score: -0.1
  penalti_sofrido:
    id: PS
    pos: [gol, zag, lat, mei, ata]
    score: 1.0
  saldo_gols:
    id: SG
    pos: [gol, zag, lat, mei, ata]
    score: 5.0
  defesa:
    id: DE
    pos: [gol]
    score: 1.0
  desarme:
    id: DS
    pos: [gol, zag, lat, mei, ata]
    score: 1.2
  gol_contra:
    id: GC
    pos: [gol, zag, lat, mei, ata]
    score: -3.0
  vermelho:
    id: CV
    pos: [gol, zag, lat, mei, ata]
    score: -3.0
  amarelo:
    id: CA
    pos: [gol, zag, lat, mei, ata]
    score: -1.0
  falta_cometida:
    id: FC
    pos: [gol, zag, lat, mei, ata]
    score: -0.3
  penalti_cometido:
    id: PC
    pos: [gol, zag, lat, mei, ata]
    score: -4.0
  defesa_penalti:
    id: DP
    pos: [gol]
    score: 7.0
  penalti_perdido:
    id: PP
    pos: [gol, zag, lat, mei, ata]
    score: -4.0

random_seed: 42