name: build
on:
    push:
        branches:
            - main
            - develop
jobs:
  train-model:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v1
        with:
            python-version: 3.8
      - name: Install requirements
        run: pip install --user -r src/requirements.txt
      - name: Test
        run: kedro test