name: build-and-evaluate
on:
    pull_request:
        branches:
            - main
            - develop
jobs:
  train-model:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: iterative/setup-cml@v1
      - uses: actions/setup-python@v1
        with:
            python-version: 3.8
      - name: Install requirements
        run: pip install --user -r src/requirements.txt
      - name: Test
        run: kedro test
      - name: Run Pipeline
        env:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
        run: |
          kedro run

          # Create CML report
          python get_metrics.py
          cat data/08_reporting/metrics.md >> report.md
          cml send-comment report.md