name: train-my-model
on: [push]
jobs:
  train-model:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: iterative/setup-cml@v1
      - uses: actions/setup-python@v1
        with:
            python-version: 3.8
      - name: Run Pipeline
        env:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
        run: |
          pip install -r src/requirements.txt
          kedro run

          # Create CML report
          python get_metrics.py
          cat data/08_reporting/metrics.md >> report.md
          cml send-comment report.md